### ISSUE TITLE
How Python Classes Work in Lupa 

### ISSUE THREAD

**Issue by SoulSen** [scoder/lupa#117]
I want to know how Python classes in the Lua environment works, I've created a class with an abstract method in Python and want to figure out how I could implement it from Lua or if subclassing is possible.

**Comment by scoder** [comment]
Good question. That's not currently supported – nor really intended. I have my doubts that subclassing across the language boundaries can really be done, but wouldn't stop anyone from trying to implement it.

You didn't say anything about your use case, but there is probably an alternative to achieve what you actually want (whatever that is). You could pass a function into the class constructor and call that instead of the abstract method, for example. That's probably what I would do (and then think twice if the surroundings really need to be a class).

**Comment by SoulSen** [comment]
Honestly, I was just trying to embed Lua to a game API I've been thinking about. There wasn't really much use case except me exploring and seeing the limits of Lupa, thanks a lot though anyways.
