### ISSUE TITLE
Call Python coros in Lua

### ISSUE THREAD

**Issue by SoulSen** [scoder/lupa#120]
How could I call Python coroutines within Lua? I haven't seen this in the documentation unless I'm blind.

**Comment by scoder** [comment]
I don't know. How would you like it to work?

**Comment by SoulSen** [comment]
Not sure if it would be a good idea or design, but maybe just on the function call, it would create the coroutine automatically? So like, 
```lua
coro()
``` 
is equivalent to 
```python
await coro()
``` 
I'm open to more ideas though, like for now to this what I do, 
```python
import asyncio

lua = LuaRuntime()
lua.globals()["coroutine"] = asyncio.create_task
```
```lua
coroutine(coro())
```

**Comment by scoder** [comment]
Could you please present a complete use case that shows how you want Python and Lua to interact here? From your description, I cannot see yet what you are trying to achieve. For example, Python has an Awaitable protocol, Lua doesn't. In what way do you want to use Lua coroutines in Python or vice versa? Using what kind of tools or frameworks.

**Comment by SoulSen** [comment]
So what my use case is, that there is this library called `discord.py`. I'm not sure if you have any idea what it is, but it's a framework to create bots for the chatting platform Discord. For my bot, I want to add scripting, so they can add their own "custom" commands and stuff. Though, the library is async, so you must call coroutines for certain functions. What my idea that I presented above to be able to use Python coroutines within Lua, is to automatically await it when it's called.

**Comment by scoder** [comment]
The thing is, the way coroutines work in Python is not magic. It's a protocol. Lua coroutines do not implement that protocol.

As far as I understand it so far, you wouldn't need anything from Lupa side for this. But you need to implement some kind of wrapper for Lua coroutines that maps a specific behaviour of a coroutine that your users would have to implement to the Python Awaitable protocol.

You probably can't map arbitrary Lua coroutines that way, but it should be possible to pass a Python API into the Lua code that your users could then use to map their async operations to what the Python framework expects.

I'll close this ticket, since I do not see anything that Lupa could (or should) help with here. I think an async integration between (a specific kind of) Lua coroutines with Python async frameworks might best be provided as a separate PyPI package that people can install in addition to Lupa.

**Comment by SoulSen** [comment]
If anyone is looking for a solution for this problem check [AsyncLupa](https://github.com/SoulSen/AsyncLupa)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
