### ISSUE TITLE
expose lua C APIs and ``lua_State`` object

### ISSUE THREAD

**Issue by TitanSnow** [scoder/lupa#92]
expose all or a limited subset of lua C APIs and the ``lua_State`` object to make it able to do low-level operations like syntax check

**Comment by scoder** [comment]
I'm not sure I understand your use case. How is a "syntax check" a low-level operation?

But the main question is: what level of safety should that C-API provide? The LuaRuntime uses locking, for example. Should that be exposed or even enforced? Should there be access to the ``lua_State`` while it is running?

How do you envision the usage of that C-API? Would you expect external packages to compile against Lupa and use it in order to extend Lupa? And, wouldn't Lua be a better extension language here than C or Cython?

**Comment by TitanSnow** [comment]
> I'm not sure I understand your use case. How is a "syntax check" a low-level operation?

`luaL_loadbuffer` returns `LUA_ERRSYNTAX` when there's syntax error. In this way I could know whether a snippet of code is wrong on syntax without running it. As you can know it's important to write a REPL because REPL should know one line user typed is already finished or not and whether to wait for more input

> The LuaRuntime uses locking, for example. Should that be exposed or even enforced?

My option is to mark these APIs as "non thread-safe" and let user lock by themselves

**Comment by scoder** [comment]
> luaL_loadbuffer returns LUA_ERRSYNTAX when there's syntax error.

You currently get a `LuaSyntaxError` exception in that case. If that's not enough, I think the obvious first step would be to increase the amount of information provided by that exception, rather than stepping down to the C level. If your goal is to implement a Lua REPL on top of Lupa, that should be possible in Python, without resorting to C.

> My option is to mark these APIs as "non thread-safe" and let user lock by themselves.

Which then suggests that either the `LuaRuntime` or its lock would have to get exposed. I'd rather like to avoid that...

If the C-API is purely function based, however, it could avoid exposing the runtime all together. There could be functions `int lock_runtime(object) except -1` and `int unlock_runtime(object) except -1` that could cast and lock/unlock. And a function `lua_State* get_lua_state(object) except NULL` that would return the `lua_State*` of the `LuaRuntime` that was passed in. Simple and unsafe. And a bit ugly, but well, at least simple enough to be ugly for good. Anything else you would need?

**Comment by TitanSnow** [comment]
> If that's not enough, I think the obvious first step would be to increase the amount of information provided by that exception, rather than stepping down to the C level.

The ways in lupa to load lua code are only `.eval()` and `.execute()`. I'm wondering if it is better to add something like `.check()` -- only load and check the code, but not run it. It might be useful for doing static analysis

> If the C-API is purely function based, however, it could avoid exposing the runtime all together. There could be functions int lock_runtime(object) except -1 and int unlock_runtime(object) except -1 that could cast and lock/unlock. And a function lua_State* get_lua_state(object) except NULL that would return the lua_State* of the LuaRuntime that was passed in. Simple and unsafe. And a bit ugly, but well, at least simple enough to be ugly for good. Anything else you would need?

I prefer to make them as methods of LuaRuntime object. For locking, I think the allocation, acquiring and releasing are all users' job. lupa doesn't have to expose internal locking interface -- better to expose, easy for users -- and users could use `threading.RLock` by themselves

For my implement, ffilupa, I do not expose locking interface, and expose a property -- `lua_state` of each LuaRuntime object like this

```python
@property
def lua_state(self):
    """the pointer to ``lua_State`` object"""
    return self._state
```

the lua APIs are in a submodule `ffilupa.lua`. I can use

```python
ffilupa.lua.ffi.string(ffilupa.lua.lib.lua_tostring(runtime.lua_state, -1))
```

to get a string on the top of stack

**Comment by scoder** [comment]
> users could use threading.RLock by themselves

No, they can't. There is one lock for the runtime. Using a different one will not prevent the runtime from being used concurrently.

> [...] to get a string on the top of stack

Well, users really shouldn't be doing that. It defeats the purpose of encapsulation of state and kills assumptions that the runtime can otherwise take for granted inside of its own code. The C-API should certainly not be exposed at the Python level.

> I'm wondering if it is better to add something like .check() -- only load and check the code

It would still create an executable object on success, right? Then I wouldn't call it `.check()` but `.compile()`, maybe? And return a reference to the object, so that it can be called later?

**Comment by TitanSnow** [comment]
> No, they can't. There is one lock for the runtime. Using a different one will not prevent the runtime from being used concurrently.

I mean when using non thread-safe low-level APIs, users could use their own lock. When using high-level APIs, users shouldn't, and don't have to use any lock by themselves

> It would still create an executable object on success, right? Then I wouldn't call it .check() but .compile(), maybe? And return a reference to the object, so that it can be called later?

Great idea

> It defeats the purpose of encapsulation of state and kills assumptions that the runtime can otherwise take for granted inside of its own code.

Well, there are always features lua APIs can provide and lupa cannot. If encapsulation gets into the way of more features, I prefer to break the encapsulation a little.

For the assumptions of runtime, it's users' duty to make sure the stack is unchanged before and after one operation so that no assumptions would be broken

**Comment by scoder** [comment]
Is this ticket still relevant?
